name: GitHub Actions Deploy to Pages
run-name: ${{ github.actor }} is deploying a build to GitHub Pages
on: 
  push:
    branches:
      - main

jobs:
  Setup-Angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@18
      - name: Build
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: Upload to AWS
        run: |
          cd "./dist/trentiumz/browser"
          aws s3 cp . s3://trentium.ca --recursive