name: GitHub Actions Setup Deploy Angular!
run-name: ${{ github.actor }} is setting up Angular
on: [push]

jobs:
  Setup-Angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "checking out ${{ github.repository }}"
      - run: cd ${{ github.workspace }}
      - name: use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'
      - run: npm install
      - run: ng build
      - run: |
          ls ${{ github.workspace }}
      - run: echo "done??"