name: GitHub Actions Deploy to Pages
run-name: ${{ github.actor }} is deploying a build to GitHub Pages
on: 
  push:
    branches:
      - main

jobs:
  Deploy-To-Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - run: git checkout github-static
      - run: git pull
      - name: use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@18
      - name: Build
        run: ng build --output-path "docs"
      - name: Authenticate
        run: |
          git config --global user.email "danielyeqt@gmail.com"
          git config --global user.name "Trentiumz"
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Site for ${{ github.run_id }}"
          git push origin HEAD:github-static  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 