name: GitHub Actions Setup Deploy Angular!
run-name: ${{ github.actor }} is setting up Angular
on: [push]

jobs:
  Setup-Angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Move to workspace
        run: cd ${{ github.workspace }}
      - name: use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli@18
      - name: Build
        run: npm run build
      - name: Move to browser
        run: cd "./dist/browser"
      - run: ls ${{ github.workspace }}